version: "3.9"

services:
  web:
    container_name: voyager-web
    image: voyager-web:latest
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    env_file:
      - .env
    networks:
      - postgresdatabase_postgres_network

networks:
  postgresdatabase_postgres_network:
    external: true



  # cloudflared:
  #   container_name: cloudflared
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel --no-autoupdate run --token <SEU_TOKEN>
  #   restart: always
  #   networks:
  #     - metanet1

